### ISSUE TITLE
rigs2 not showing all workers

### ISSUE THREAD

**Issue by alkesh-github** [makeSmartio/niceHashHistory_Docker#4]
rigs2 does not report my unmanaged miners.  It does pick up my managed miner\
activeworkers works perfectly.

<img width="873" alt="Screen Shot 2021-05-03 at 3 45 36 PM" src="https://user-images.githubusercontent.com/60115195/116925045-af04e380-ac26-11eb-8196-107d4ab61161.png">
<img width="918" alt="Screen Shot 2021-05-03 at 3 45 45 PM" src="https://user-images.githubusercontent.com/60115195/116925047-af9d7a00-ac26-11eb-8171-f9c44b490a9c.png">

**Comment by makeSmartio** [comment]
This service can only report on what NiceHash puts in the API response, which, as you have pointed out, is only the managed miners.
